# ~/.config/starship.toml

[[battery.display]]
threshold = 25
style = "bold red"

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 15_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 10
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "branch "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "⚔️ "
ahead = "ahead ×${count} "
behind = "behind ×${count} "
diverged = "diverged ahead ×${ahead_count} behind ×${behind_count} "
untracked = "untracked ×${count} "
stashed = "stashed "
modified = "modified ×${count} "
staged = "staged ×${count} "
renamed = "renamed ×${count} "
deleted = "deleted ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[typst]
format = "[$symbol($version)]($style)"
style = "bold #239dae"

[username]
style_user = "bold dimmed blue"
show_always = false

[nodejs]
format = "via [nodejs $version](bold green) "

[dotnet]
format = "via [dotnet($version )(target $tfm )]($style)"
